name: Generate Maps Manifest

on:
  schedule:
    - cron: '0 3 * * *' # Läuft vollautomatisch jede Nacht um 03:00 Uhr
  workflow_dispatch: # Erlaubt dir, das Update jederzeit manuell im GitHub-Tab "Actions" anzustoßen

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig: Erlaubt dem Skript, die neue json-Datei ins Repo hochzuladen

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Manifest generieren
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python generate_manifest.py

    - name: Manifest ins Repository pushen
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add maps_manifest.json
        # Nur committen und pushen, wenn sich an den Dateien in den Releases etwas geändert hat
        git diff-index --quiet HEAD || git commit -m "Automatisches Update der maps_manifest.json" -a
        git push
